In [1]:
# Prototype for dashboard computations

# Performance
# ytd perf

# Risk
# 20-day historical vol
# 1-day VaR

# Just storing stuff in the DB. Only portfolio level for now
# First compute portfolio values

In [48]:
from worker.database import connect

import polars as pl
import datetime

In [97]:
DATE = datetime.date(2025, 8, 29)
DATE_CALC_START = datetime.date(2023, 9, 1)
DATE_START = datetime.date(2018, 9, 1)

with connect() as session:
    df_positions = pl.read_database(
        """
        SELECT
            portfolio_id::TEXT as portfolio_id,
            date,
            instrument_id::TEXT as instrument_id,
            quantity
        FROM ptf_comp
        WHERE date <= :date_end
        AND date >= :date_start
    """,
        session,
        execute_options={"params": {"date_end": DATE, "date_start": DATE_CALC_START}},
    )

    u_insts = df_positions["instrument_id"].unique().to_list()

    df_market_data = pl.read_database(
        """
        SELECT
            instrument_id::TEXT as instrument_id,
            date,
            value as price
        FROM market_data
        WHERE 1=1
        AND date >= :date_start
        AND date <= :date_end
        AND instrument_id::TEXT = ANY(:insts)
        AND data_type = 'adj_close'
    """,
        session,
        execute_options={"params": {"date_start": DATE_START, "date_end": DATE, "insts": u_insts}},
    )

In [98]:
df_positions

shape: (150, 4)
┌─────────────────────────────────┬────────────┬─────────────────────────────────┬───────────────┐
│ portfolio_id                    ┆ date       ┆ instrument_id                   ┆ quantity      │
│ ---                             ┆ ---        ┆ ---                             ┆ ---           │
│ str                             ┆ date       ┆ str                             ┆ decimal[*,8]  │
╞═════════════════════════════════╪════════════╪═════════════════════════════════╪═══════════════╡
│ e3a50d76-dcb7-4377-8ad3-8ff9f4… ┆ 2025-08-29 ┆ fb39c249-6cb1-47b6-9220-6c0f8d… ┆ 1000.00000000 │
│ 4daf79fe-feb9-4c5a-ba1f-a67b96… ┆ 2025-08-29 ┆ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 1000.00000000 │
│ d7da851b-20c5-4de0-9c93-68a9f1… ┆ 2025-08-29 ┆ 02f2fb63-27d1-43bf-953d-7249c4… ┆ 1000.00000000 │
│ 0b209d5c-12ed-48af-a597-b1e22f… ┆ 2025-08-29 ┆ 41712141-41c4-4e22-83d1-8cc45c… ┆ 1000.00000000 │
│ f4dd8467-36cf-4d10-93d3-a0699a… ┆ 2025-08-29 ┆ c135cb6f-2a23-4032-ae80-856a31… ┆ 1000.00000000 │
│ …                               ┆ …          ┆ …                               ┆ …             │
│ 74623cfa-69a7-43c4-a6e5-3beb9b… ┆ 2025-08-26 ┆ 35a6016b-daf4-40a4-84d1-c5492a… ┆ 1000.00000000 │
│ 73b9f260-1100-469b-99a2-3a5f9e… ┆ 2025-08-26 ┆ 56cfb131-8c13-4e90-a0e9-55f93e… ┆ 1000.00000000 │
│ 67756108-d9ee-44e0-ac13-0e133d… ┆ 2025-08-26 ┆ 07602a17-b596-47d1-adc2-bda6d3… ┆ 1000.00000000 │
│ 78e37b84-0a65-4f70-a706-ae0175… ┆ 2025-08-26 ┆ 39a5e158-c52e-447d-a20e-180129… ┆ 1000.00000000 │
│ 594e712e-88b9-4bd8-ae5e-0ea97f… ┆ 2025-08-26 ┆ 455dda36-171f-4412-baf4-3674c6… ┆ 1000.00000000 │
└─────────────────────────────────┴────────────┴─────────────────────────────────┴───────────────┘

In [88]:
def with_returns(df: pl.DataFrame, date_col: str, value_col: str) -> pl.DataFrame:
    return df.sort(date_col).with_columns(returns=pl.col(value_col).pct_change()).drop_nulls()


def with_vols(df: pl.DataFrame, date_col: str, returns_col: str) -> pl.DataFrame:
    return (
        df.sort(date_col)
        .with_row_index(name="idx")
        .with_columns(vol=pl.col(returns_col).rolling("idx", period="20i"))
        .with_columns(vol=pl.when(pl.col("vol").list.len() == 20).then(pl.col("vol").list.std()).otherwise(None))
        .drop("idx")
    )


df_exante_perf = (
    df_positions.join(df_market_data, on="instrument_id")
    .with_columns(value=pl.col("quantity") * pl.col("price"))
    .group_by("portfolio_id", "date")
    .agg(value=pl.col("value").sum())
    .group_by("portfolio_id")
    .map_groups(lambda df: with_returns(df, date_col="date", value_col="value"))
)

In [ ]:
df_rolling_vols = df_exante_perf.group_by("portfolio_id").map_groups(
    lambda df: with_vols(df, date_col="date", returns_col="returns")
)

df_rolling_vols

shape: (86_705, 5)
┌─────────────────────────────────┬────────────┬────────────────────────────┬───────────┬──────────┐
│ portfolio_id                    ┆ date       ┆ value                      ┆ returns   ┆ vol      │
│ ---                             ┆ ---        ┆ ---                        ┆ ---       ┆ ---      │
│ str                             ┆ date       ┆ decimal[*,20]              ┆ f64       ┆ f64      │
╞═════════════════════════════════╪════════════╪════════════════════════════╪═══════════╪══════════╡
│ b872c12a-2db2-4898-a52d-4f09e8… ┆ 2018-09-05 ┆ 58818.47382130000000000000 ┆ -0.005471 ┆ null     │
│ b872c12a-2db2-4898-a52d-4f09e8… ┆ 2018-09-06 ┆ 58599.60553170000000000000 ┆ -0.003721 ┆ null     │
│ b872c12a-2db2-4898-a52d-4f09e8… ┆ 2018-09-07 ┆ 57962.03268810000000000000 ┆ -0.01088  ┆ null     │
│ b872c12a-2db2-4898-a52d-4f09e8… ┆ 2018-09-10 ┆ 58380.73724210000000000000 ┆ 0.007224  ┆ null     │
│ b872c12a-2db2-4898-a52d-4f09e8… ┆ 2018-09-11 ┆ 58266.54509100000000000000 ┆ -0.001956 ┆ null     │
│ …                               ┆ …          ┆ …                          ┆ …         ┆ …        │
│ f5764652-eca7-48f2-b621-b5fdff… ┆ 2025-08-22 ┆ 62990.00000000000000000000 ┆ 0.011725  ┆ 0.004533 │
│ f5764652-eca7-48f2-b621-b5fdff… ┆ 2025-08-25 ┆ 62720.00000000000000000000 ┆ -0.004286 ┆ 0.004539 │
│ f5764652-eca7-48f2-b621-b5fdff… ┆ 2025-08-26 ┆ 62850.00000000000000000000 ┆ 0.002073  ┆ 0.004547 │
│ f5764652-eca7-48f2-b621-b5fdff… ┆ 2025-08-27 ┆ 62840.00000000000000000000 ┆ -0.000159 ┆ 0.004453 │
│ f5764652-eca7-48f2-b621-b5fdff… ┆ 2025-08-28 ┆ 63010.00000000000000000000 ┆ 0.002705  ┆ 0.004386 │
└─────────────────────────────────┴────────────┴────────────────────────────┴───────────┴──────────┘

In [94]:
def with_historical_vars(df: pl.DataFrame, n: int, cf: float, returns_col: str) -> pl.DataFrame:
    return (
        df.with_row_index(name="idx")
        .with_columns(rolled_returns=pl.col(returns_col).rolling("idx", period=f"{n}i"))
        .with_columns(
            var=pl.when(pl.col("rolled_returns").list.len() == n)
            .then(pl.col("rolled_returns").list.eval(pl.element().quantile(1 - cf)).list.get(0))
            .otherwise(None)
        )
    )


df_rolling_historical_var = df_rolling_vols.group_by("portfolio_id").map_groups(
    lambda df: with_historical_vars(df, n=500, cf=0.99, returns_col="returns")
)

In [95]:
df_rolling_historical_var

shape: (86_705, 8)
┌──────┬──────────────┬────────────┬──────────────┬───────────┬──────────┬─────────────┬───────────┐
│ idx  ┆ portfolio_id ┆ date       ┆ value        ┆ returns   ┆ vol      ┆ rolled_retu ┆ var       │
│ ---  ┆ ---          ┆ ---        ┆ ---          ┆ ---       ┆ ---      ┆ rns         ┆ ---       │
│ u32  ┆ str          ┆ date       ┆ decimal[*,20 ┆ f64       ┆ f64      ┆ ---         ┆ f64       │
│      ┆              ┆            ┆ ]            ┆           ┆          ┆ list[f64]   ┆           │
╞══════╪══════════════╪════════════╪══════════════╪═══════════╪══════════╪═════════════╪═══════════╡
│ 0    ┆ 0b209d5c-12e ┆ 2018-09-05 ┆ 39717.539168 ┆ -0.014411 ┆ null     ┆ [-0.014411] ┆ null      │
│      ┆ d-48af-a597- ┆            ┆ 600000000000 ┆           ┆          ┆             ┆           │
│      ┆ b1e22f…      ┆            ┆ 00           ┆           ┆          ┆             ┆           │
│ 1    ┆ 0b209d5c-12e ┆ 2018-09-06 ┆ 39755.619263 ┆ 0.000959  ┆ null     ┆ [-0.014411, ┆ null      │
│      ┆ d-48af-a597- ┆            ┆ 700000000000 ┆           ┆          ┆ 0.000959]   ┆           │
│      ┆ b1e22f…      ┆            ┆ 00           ┆           ┆          ┆             ┆           │
│ 2    ┆ 0b209d5c-12e ┆ 2018-09-07 ┆ 39555.698764 ┆ -0.005029 ┆ null     ┆ [-0.014411, ┆ null      │
│      ┆ d-48af-a597- ┆            ┆ 500000000000 ┆           ┆          ┆ 0.000959,   ┆           │
│      ┆ b1e22f…      ┆            ┆ 00           ┆           ┆          ┆ -0.00502…   ┆           │
│ 3    ┆ 0b209d5c-12e ┆ 2018-09-10 ┆ 39165.377789 ┆ -0.009868 ┆ null     ┆ [-0.014411, ┆ null      │
│      ┆ d-48af-a597- ┆            ┆ 900000000000 ┆           ┆          ┆ 0.000959, … ┆           │
│      ┆ b1e22f…      ┆            ┆ 00           ┆           ┆          ┆ -0.009…     ┆           │
│ 4    ┆ 0b209d5c-12e ┆ 2018-09-11 ┆ 39251.058003 ┆ 0.002188  ┆ null     ┆ [-0.014411, ┆ null      │
│      ┆ d-48af-a597- ┆            ┆ 900000000000 ┆           ┆          ┆ 0.000959, … ┆           │
│      ┆ b1e22f…      ┆            ┆ 00           ┆           ┆          ┆ 0.0021…     ┆           │
│ …    ┆ …            ┆ …          ┆ …            ┆ …         ┆ …        ┆ …           ┆ …         │
│ 1747 ┆ 925a0ff5-325 ┆ 2025-08-22 ┆ 22570.000000 ┆ 0.004898  ┆ 0.007212 ┆ [0.016548,  ┆ -0.029006 │
│      ┆ 8-44c4-86eb- ┆            ┆ 000000000000 ┆           ┆          ┆ -0.002791,  ┆           │
│      ┆ 3de00c…      ┆            ┆ 00           ┆           ┆          ┆ … 0.0048…   ┆           │
│ 1748 ┆ 925a0ff5-325 ┆ 2025-08-25 ┆ 22710.000000 ┆ 0.006203  ┆ 0.006735 ┆ [-0.002791, ┆ -0.029006 │
│      ┆ 8-44c4-86eb- ┆            ┆ 000000000000 ┆           ┆          ┆ 0.003731, … ┆           │
│      ┆ 3de00c…      ┆            ┆ 00           ┆           ┆          ┆ 0.0062…     ┆           │
│ 1749 ┆ 925a0ff5-325 ┆ 2025-08-26 ┆ 22520.000000 ┆ -0.008366 ┆ 0.006272 ┆ [0.003731,  ┆ -0.029006 │
│      ┆ 8-44c4-86eb- ┆            ┆ 000000000000 ┆           ┆          ┆ 0.0, …      ┆           │
│      ┆ 3de00c…      ┆            ┆ 00           ┆           ┆          ┆ -0.008366]  ┆           │
│ 1750 ┆ 925a0ff5-325 ┆ 2025-08-27 ┆ 22590.000000 ┆ 0.003108  ┆ 0.006301 ┆ [0.0,       ┆ -0.029006 │
│      ┆ 8-44c4-86eb- ┆            ┆ 000000000000 ┆           ┆          ┆ 0.008364, … ┆           │
│      ┆ 3de00c…      ┆            ┆ 00           ┆           ┆          ┆ 0.003108]   ┆           │
│ 1751 ┆ 925a0ff5-325 ┆ 2025-08-28 ┆ 22720.000000 ┆ 0.005755  ┆ 0.006021 ┆ [0.008364,  ┆ -0.029006 │
│      ┆ 8-44c4-86eb- ┆            ┆ 000000000000 ┆           ┆          ┆ 0.014286, … ┆           │
│      ┆ 3de00c…      ┆            ┆ 00           ┆           ┆          ┆ 0.00575…    ┆           │
└──────┴──────────────┴────────────┴──────────────┴───────────┴──────────┴─────────────┴───────────┘

In [72]:
df_exante_perf

shape: (86_705, 4)
┌─────────────────────────────────┬────────────┬─────────────────────────────┬───────────┐
│ portfolio_id                    ┆ date       ┆ value                       ┆ returns   │
│ ---                             ┆ ---        ┆ ---                         ┆ ---       │
│ str                             ┆ date       ┆ decimal[*,20]               ┆ f64       │
╞═════════════════════════════════╪════════════╪═════════════════════════════╪═══════════╡
│ 78e37b84-0a65-4f70-a706-ae0175… ┆ 2018-09-05 ┆ 87373.96029150000000000000  ┆ -0.001001 │
│ 78e37b84-0a65-4f70-a706-ae0175… ┆ 2018-09-06 ┆ 86722.35128220000000000000  ┆ -0.007458 │
│ 78e37b84-0a65-4f70-a706-ae0175… ┆ 2018-09-07 ┆ 86527.84113020000000000000  ┆ -0.002243 │
│ 78e37b84-0a65-4f70-a706-ae0175… ┆ 2018-09-10 ┆ 86625.09620620000000000000  ┆ 0.001124  │
│ 78e37b84-0a65-4f70-a706-ae0175… ┆ 2018-09-11 ┆ 86654.27272900000000000000  ┆ 0.000337  │
│ …                               ┆ …          ┆ …                           ┆ …         │
│ 16cc08b3-c767-464d-8d9c-573d4d… ┆ 2025-08-22 ┆ 648500.00000000000000000000 ┆ 0.015344  │
│ 16cc08b3-c767-464d-8d9c-573d4d… ┆ 2025-08-25 ┆ 645640.00000000000000000000 ┆ -0.00441  │
│ 16cc08b3-c767-464d-8d9c-573d4d… ┆ 2025-08-26 ┆ 648260.00000000000000000000 ┆ 0.004058  │
│ 16cc08b3-c767-464d-8d9c-573d4d… ┆ 2025-08-27 ┆ 649800.00000000000000000000 ┆ 0.002376  │
│ 16cc08b3-c767-464d-8d9c-573d4d… ┆ 2025-08-28 ┆ 652140.00000000000000000000 ┆ 0.003601  │
└─────────────────────────────────┴────────────┴─────────────────────────────┴───────────┘

In [ ]:
df_rolling_vol = ()

In [60]:
df_market_data

shape: (86_755, 3)
┌─────────────────────────────────┬────────────┬────────────────┐
│ instrument_id                   ┆ date       ┆ price          │
│ ---                             ┆ ---        ┆ ---            │
│ str                             ┆ date       ┆ decimal[*,10]  │
╞═════════════════════════════════╪════════════╪════════════════╡
│ 3c7f3c30-4848-48ce-b2a5-3fc1b9… ┆ 2025-08-28 ┆ 37.6700000000  │
│ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 2025-08-28 ┆ 87.2200000000  │
│ 491f4737-7acc-4f1a-b486-e6cc01… ┆ 2025-08-28 ┆ 111.2900000000 │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… ┆ 2025-08-28 ┆ 73.0900000000  │
│ 07602a17-b596-47d1-adc2-bda6d3… ┆ 2025-08-28 ┆ 72.7300000000  │
│ …                               ┆ …          ┆ …              │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… ┆ 2018-11-05 ┆ 42.0968737433  │
│ c6d94933-a248-4df5-a56e-b2c0c0… ┆ 2018-11-05 ┆ 102.3831230164 │
│ 5817580d-febb-47d3-a1dd-70cae7… ┆ 2018-11-05 ┆ 22.8190594604  │
│ 22440153-44ce-4830-a6b1-1d7232… ┆ 2018-11-05 ┆ 105.9081132910 │
│ 6444a8ec-8304-4918-a36d-076672… ┆ 2018-11-05 ┆ 139.9508843233 │
└─────────────────────────────────┴────────────┴────────────────┘

In [58]:
df_market_data

shape: (86_755, 4)
┌─────────────────────────────────┬────────────┬───────────┬────────────────┐
│ instrument_id                   ┆ date       ┆ data_type ┆ value          │
│ ---                             ┆ ---        ┆ ---       ┆ ---            │
│ object                          ┆ date       ┆ str       ┆ decimal[*,10]  │
╞═════════════════════════════════╪════════════╪═══════════╪════════════════╡
│ 3c7f3c30-4848-48ce-b2a5-3fc1b9… ┆ 2025-08-28 ┆ adj_close ┆ 37.6700000000  │
│ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 2025-08-28 ┆ adj_close ┆ 87.2200000000  │
│ 491f4737-7acc-4f1a-b486-e6cc01… ┆ 2025-08-28 ┆ adj_close ┆ 111.2900000000 │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… ┆ 2025-08-28 ┆ adj_close ┆ 73.0900000000  │
│ 07602a17-b596-47d1-adc2-bda6d3… ┆ 2025-08-28 ┆ adj_close ┆ 72.7300000000  │
│ …                               ┆ …          ┆ …         ┆ …              │
│ e24878f5-b374-4d80-ba37-234362… ┆ 2018-09-04 ┆ adj_close ┆ 44.1677008316  │
│ 41712141-41c4-4e22-83d1-8cc45c… ┆ 2018-09-04 ┆ adj_close ┆ 40.2982606186  │
│ 929e3e08-574e-4b80-ab1d-57bdef… ┆ 2018-09-04 ┆ adj_close ┆ 44.0783497738  │
│ b784bce9-a223-49a4-9c09-9f381c… ┆ 2018-09-04 ┆ adj_close ┆ 63.0622804463  │
│ 70e9623b-1ea8-4de7-a8eb-4193d4… ┆ 2018-09-04 ┆ adj_close ┆ 21.6948309864  │
└─────────────────────────────────┴────────────┴───────────┴────────────────┘

In [ ]:
df_positions

shape: (50, 4)
┌────────────┬─────────────────────────────────┬─────────────────────────────────┬───────────────┐
│ date       ┆ portfolio_id                    ┆ instrument_id                   ┆ quantity      │
│ ---        ┆ ---                             ┆ ---                             ┆ ---           │
│ date       ┆ object                          ┆ object                          ┆ decimal[*,8]  │
╞════════════╪═════════════════════════════════╪═════════════════════════════════╪═══════════════╡
│ 2025-08-29 ┆ e3a50d76-dcb7-4377-8ad3-8ff9f4… ┆ fb39c249-6cb1-47b6-9220-6c0f8d… ┆ 1000.00000000 │
│ 2025-08-29 ┆ 4daf79fe-feb9-4c5a-ba1f-a67b96… ┆ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 1000.00000000 │
│ 2025-08-29 ┆ d7da851b-20c5-4de0-9c93-68a9f1… ┆ 02f2fb63-27d1-43bf-953d-7249c4… ┆ 1000.00000000 │
│ 2025-08-29 ┆ 0b209d5c-12ed-48af-a597-b1e22f… ┆ 41712141-41c4-4e22-83d1-8cc45c… ┆ 1000.00000000 │
│ 2025-08-29 ┆ f4dd8467-36cf-4d10-93d3-a0699a… ┆ c135cb6f-2a23-4032-ae80-856a31… ┆ 1000.00000000 │
│ …          ┆ …                               ┆ …                               ┆ …             │
│ 2025-08-29 ┆ f0085a41-9c45-4bd5-8a9b-456a31… ┆ 727b0b7c-268d-42c4-bb48-11020f… ┆ 1000.00000000 │
│ 2025-08-29 ┆ ca366c28-aff3-45f6-ae3b-37079c… ┆ 6444a8ec-8304-4918-a36d-076672… ┆ 1000.00000000 │
│ 2025-08-29 ┆ 67756108-d9ee-44e0-ac13-0e133d… ┆ 07602a17-b596-47d1-adc2-bda6d3… ┆ 1000.00000000 │
│ 2025-08-29 ┆ f5764652-eca7-48f2-b621-b5fdff… ┆ 29fcfd80-cc50-483f-b2f1-a70992… ┆ 1000.00000000 │
│ 2025-08-29 ┆ 78e37b84-0a65-4f70-a706-ae0175… ┆ 39a5e158-c52e-447d-a20e-180129… ┆ 1000.00000000 │
└────────────┴─────────────────────────────────┴─────────────────────────────────┴───────────────┘

In [19]:
holdings

[<worker.database.Holding at 0x117ccaeb0>,
 <worker.database.Holding at 0x117ccb8c0>,
 <worker.database.Holding at 0x117ccb930>,
 <worker.database.Holding at 0x117ccbaf0>,
 <worker.database.Holding at 0x117ccbb60>,
 <worker.database.Holding at 0x117ccba10>,
 <worker.database.Holding at 0x117ccba80>,
 <worker.database.Holding at 0x117ccbd20>,
 <worker.database.Holding at 0x117ccbbd0>,
 <worker.database.Holding at 0x117ccbc40>,
 <worker.database.Holding at 0x117ccbcb0>,
 <worker.database.Holding at 0x117ccbe00>,
 <worker.database.Holding at 0x117ccbd90>,
 <worker.database.Holding at 0x117ccbe70>,
 <worker.database.Holding at 0x117ccbee0>,
 <worker.database.Holding at 0x117ccbf50>,
 <worker.database.Holding at 0x120298050>,
 <worker.database.Holding at 0x1202980c0>,
 <worker.database.Holding at 0x120298130>,
 <worker.database.Holding at 0x1202981a0>,
 <worker.database.Holding at 0x120298210>,
 <worker.database.Holding at 0x120298280>,
 <worker.database.Holding at 0x1202982f0>,
 <worker.database.Holding at 0x120298360>,
 <worker.database.Holding at 0x1202983d0>,
 <worker.database.Holding at 0x120298440>,
 <worker.database.Holding at 0x1202984b0>,
 <worker.database.Holding at 0x120298520>,
 <worker.database.Holding at 0x120298590>,
 <worker.database.Holding at 0x120298600>,
 <worker.database.Holding at 0x120298670>,
 <worker.database.Holding at 0x1202986e0>,
 <worker.database.Holding at 0x120298750>,
 <worker.database.Holding at 0x1202987c0>,
 <worker.database.Holding at 0x120298830>,
 <worker.database.Holding at 0x1202988a0>,
 <worker.database.Holding at 0x120298910>,
 <worker.database.Holding at 0x120298980>,
 <worker.database.Holding at 0x1202989f0>,
 <worker.database.Holding at 0x120298a60>,
 <worker.database.Holding at 0x120298ad0>,
 <worker.database.Holding at 0x120298b40>,
 <worker.database.Holding at 0x120298bb0>,
 <worker.database.Holding at 0x120298c20>,
 <worker.database.Holding at 0x120298c90>,
 <worker.database.Holding at 0x120298d00>,
 <worker.database.Holding at 0x120298d70>,
 <worker.database.Holding at 0x120298de0>,
 <worker.database.Holding at 0x120298e50>,
 <worker.database.Holding at 0x120298ec0>]

In [13]:
portfolios_dict

{UUID('bd3425c7-1dea-44bd-b345-d7517316f314'): {'portfolio': <worker.database.Portfolio at 0x11780fa10>,
  'holdings': [<worker.database.Holding at 0x116f56040>]},
 UUID('30ecbfb2-2fa9-4611-afcf-8b8fd61aa429'): {'portfolio': <worker.database.Portfolio at 0x11780fa80>,
  'holdings': [<worker.database.Holding at 0x116f54750>]},
 UUID('7509fde2-c757-486d-9b53-90f28b5d5a0c'): {'portfolio': <worker.database.Portfolio at 0x11780faf0>,
  'holdings': [<worker.database.Holding at 0x116f546e0>]},
 UUID('6c5d5b6e-f50a-40fe-ba5e-b208e1ecb458'): {'portfolio': <worker.database.Portfolio at 0x11780cde0>,
  'holdings': [<worker.database.Holding at 0x116f55cc0>]},
 UUID('24d4e3a0-5ea6-4ace-b18a-8ac9a16fcb8e'): {'portfolio': <worker.database.Portfolio at 0x11780dbe0>,
  'holdings': [<worker.database.Holding at 0x116f54670>]},
 UUID('2b8e2f4b-c492-4521-89f3-0a4f8a2afcb1'): {'portfolio': <worker.database.Portfolio at 0x11780d240>,
  'holdings': [<worker.database.Holding at 0x116f55c50>]},
 UUID('6528a25b-f12e-43aa-8d14-7faa56f71278'): {'portfolio': <worker.database.Portfolio at 0x11780fb60>,
  'holdings': [<worker.database.Holding at 0x116f54600>]},
 UUID('02105032-08f7-48b5-92f2-a4fdf3f81840'): {'portfolio': <worker.database.Portfolio at 0x11780fbd0>,
  'holdings': [<worker.database.Holding at 0x116f55be0>]},
 UUID('6e29d09a-5559-40ec-b473-0dee1315db94'): {'portfolio': <worker.database.Portfolio at 0x11780fc40>,
  'holdings': [<worker.database.Holding at 0x116f54590>]},
 UUID('9c41728b-c00f-4d4c-8c53-44d0fcb00c6d'): {'portfolio': <worker.database.Portfolio at 0x11780fcb0>,
  'holdings': [<worker.database.Holding at 0x116f54520>]},
 UUID('041e4244-f4c9-4699-bfce-81cf527d3711'): {'portfolio': <worker.database.Portfolio at 0x11780fd20>,
  'holdings': [<worker.database.Holding at 0x116f55b70>]},
 UUID('a6185e5b-14af-4d3e-a496-34bf80dd26b2'): {'portfolio': <worker.database.Portfolio at 0x11780fd90>,
  'holdings': [<worker.database.Holding at 0x116f54440>]},
 UUID('faffb1de-06f3-47f1-92ad-ec27796b807f'): {'portfolio': <worker.database.Portfolio at 0x11780fe00>,
  'holdings': [<worker.database.Holding at 0x116f55b00>]},
 UUID('74b13d77-71c9-4a5e-96cf-8e4b132de846'): {'portfolio': <worker.database.Portfolio at 0x11780fe70>,
  'holdings': [<worker.database.Holding at 0x116f544b0>]},
 UUID('b2b57150-bc42-4948-9465-8c8de933f75f'): {'portfolio': <worker.database.Portfolio at 0x11780fee0>,
  'holdings': [<worker.database.Holding at 0x116f559b0>]},
 UUID('2d92f54c-9f14-44e8-911c-674587f60d82'): {'portfolio': <worker.database.Portfolio at 0x11780ff50>,
  'holdings': [<worker.database.Holding at 0x116f55a90>]},
 UUID('b1a2abbb-47a3-489d-9abf-37c526a3d1a3'): {'portfolio': <worker.database.Portfolio at 0x117844050>,
  'holdings': [<worker.database.Holding at 0x116f55a20>]},
 UUID('e378decf-5e75-4b4a-ae58-cbf08243f787'): {'portfolio': <worker.database.Portfolio at 0x1178440c0>,
  'holdings': [<worker.database.Holding at 0x116f543d0>]},
 UUID('3f27a2f5-bad2-4f1a-8a9b-22995ac8fc07'): {'portfolio': <worker.database.Portfolio at 0x117844130>,
  'holdings': [<worker.database.Holding at 0x116f55940>]},
 UUID('2271ba74-4caa-42ac-8a2e-c39dd5dbb4f3'): {'portfolio': <worker.database.Portfolio at 0x1178441a0>,
  'holdings': [<worker.database.Holding at 0x116f54360>]},
 UUID('cfd71fcd-02ac-4bfe-a5d7-0a632bd2f9eb'): {'portfolio': <worker.database.Portfolio at 0x117844210>,
  'holdings': [<worker.database.Holding at 0x116f542f0>]},
 UUID('2e3c9fe5-2b23-4c8f-81f1-0b380627ccd5'): {'portfolio': <worker.database.Portfolio at 0x117844280>,
  'holdings': [<worker.database.Holding at 0x116f558d0>]},
 UUID('028b87b1-69ed-453e-8c54-b9d31a736543'): {'portfolio': <worker.database.Portfolio at 0x1178442f0>,
  'holdings': [<worker.database.Holding at 0x116f54280>]},
 UUID('f9cc04e2-a614-4e70-acfd-8e23fa37af3c'): {'portfolio': <worker.database.Portfolio at 0x117844360>,
  'holdings': [<worker.database.Holding at 0x116f55860>]},
 UUID('dfa5835d-7c8a-4717-bd85-30716bd41335'): {'portfolio': <worker.database.Portfolio at 0x1178443d0>,
  'holdings': [<worker.database.Holding at 0x116f541a0>]},
 UUID('c70e0d18-8243-4e3e-a201-949425b76045'): {'portfolio': <worker.database.Portfolio at 0x117844440>,
  'holdings': [<worker.database.Holding at 0x116f557f0>]},
 UUID('cb90f820-ba51-4ddf-8bbf-d54730cc3482'): {'portfolio': <worker.database.Portfolio at 0x1178444b0>,
  'holdings': [<worker.database.Holding at 0x11780d9b0>]},
 UUID('f9721b67-94ce-420d-b770-556cfe883ad8'): {'portfolio': <worker.database.Portfolio at 0x117844520>,
  'holdings': [<worker.database.Holding at 0x11780d320>]},
 UUID('5f6154be-2628-470d-acef-eb8e6815980b'): {'portfolio': <worker.database.Portfolio at 0x117844590>,
  'holdings': [<worker.database.Holding at 0x11780d010>]},
 UUID('86399e25-3954-47eb-bd33-91214ac7aa8a'): {'portfolio': <worker.database.Portfolio at 0x117844600>,
  'holdings': [<worker.database.Holding at 0x11780db70>]},
 UUID('65bd0c90-941b-4ff5-bafd-30ab87c5f539'): {'portfolio': <worker.database.Portfolio at 0x117844670>,
  'holdings': [<worker.database.Holding at 0x11780dd30>]},
 UUID('96b836c3-8679-4bda-b749-7c3c785ccd99'): {'portfolio': <worker.database.Portfolio at 0x1178446e0>,
  'holdings': [<worker.database.Holding at 0x11780da90>]},
 UUID('e541119f-ee43-4d52-a70c-e1d7765ec4e2'): {'portfolio': <worker.database.Portfolio at 0x117844750>,
  'holdings': [<worker.database.Holding at 0x11780dcc0>]},
 UUID('2eadb74c-b1e5-4763-8c10-e4c5c4a7a483'): {'portfolio': <worker.database.Portfolio at 0x1178447c0>,
  'holdings': [<worker.database.Holding at 0x11780de10>]},
 UUID('51fe62ab-38ea-4626-8ed0-3acc6b441cc7'): {'portfolio': <worker.database.Portfolio at 0x117844830>,
  'holdings': [<worker.database.Holding at 0x11780f310>]},
 UUID('2b703602-f3f0-42a1-97f7-cb7e9a0ab92b'): {'portfolio': <worker.database.Portfolio at 0x1178448a0>,
  'holdings': [<worker.database.Holding at 0x11780f380>]},
 UUID('f880bc04-e033-42f2-85dd-4be73588ceba'): {'portfolio': <worker.database.Portfolio at 0x117844910>,
  'holdings': [<worker.database.Holding at 0x11780f3f0>]},
 UUID('1e28aa46-048c-42e1-a098-49cf4de0ebe3'): {'portfolio': <worker.database.Portfolio at 0x117844980>,
  'holdings': [<worker.database.Holding at 0x11780f460>]},
 UUID('44bdfc21-1e6f-461d-8f96-7167be1dc543'): {'portfolio': <worker.database.Portfolio at 0x1178449f0>,
  'holdings': [<worker.database.Holding at 0x11780f4d0>]},
 UUID('e775f64e-fd39-4ed1-bc78-37f440f00e7a'): {'portfolio': <worker.database.Portfolio at 0x117844a60>,
  'holdings': [<worker.database.Holding at 0x11780f540>]},
 UUID('539128a9-170c-42f5-94bc-f9b4f1cd2956'): {'portfolio': <worker.database.Portfolio at 0x117844ad0>,
  'holdings': [<worker.database.Holding at 0x11780f5b0>]},
 UUID('502f0588-e1f3-4df9-b202-87c6e8af26ec'): {'portfolio': <worker.database.Portfolio at 0x117844b40>,
  'holdings': [<worker.database.Holding at 0x11780f620>]},
 UUID('e130aaea-4aec-4f7b-8a98-e79b344ef35c'): {'portfolio': <worker.database.Portfolio at 0x117844bb0>,
  'holdings': [<worker.database.Holding at 0x11780f690>]},
 UUID('f38a52f5-a563-4cf4-b768-a64c5026ce5d'): {'portfolio': <worker.database.Portfolio at 0x117844c20>,
  'holdings': [<worker.database.Holding at 0x11780f700>]},
 UUID('d941b6be-8ce3-4b06-9e93-fa105153a697'): {'portfolio': <worker.database.Portfolio at 0x117844c90>,
  'holdings': [<worker.database.Holding at 0x11780f770>]},
 UUID('80742dfc-60e4-45f8-85fe-0c781d070466'): {'portfolio': <worker.database.Portfolio at 0x117844d00>,
  'holdings': [<worker.database.Holding at 0x11780f7e0>]},
 UUID('45a0aba3-aa87-41bd-8e0c-79540a2cb155'): {'portfolio': <worker.database.Portfolio at 0x117844d70>,
  'holdings': [<worker.database.Holding at 0x11780f850>]},
 UUID('ebc54cae-5121-4abb-b6a3-319e53a289d5'): {'portfolio': <worker.database.Portfolio at 0x117844de0>,
  'holdings': [<worker.database.Holding at 0x11780f8c0>]},
 UUID('15cf150e-4108-4f5d-85f0-ddf047128e1d'): {'portfolio': <worker.database.Portfolio at 0x117844e50>,
  'holdings': [<worker.database.Holding at 0x11780f930>]},
 UUID('441ee929-280d-41c8-af05-4b46d6ed293c'): {'portfolio': <worker.database.Portfolio at 0x117844ec0>,
  'holdings': [<worker.database.Holding at 0x11780f9a0>]}}

In [7]:
portfolios_dict

{UUID('bd3425c7-1dea-44bd-b345-d7517316f314'): {'portfolio': <worker.database.Portfolio at 0x116f11010>,
  'holdings': [<worker.database.Holding at 0x1169875b0>]},
 UUID('30ecbfb2-2fa9-4611-afcf-8b8fd61aa429'): {'portfolio': <worker.database.Portfolio at 0x116eede50>,
  'holdings': [<worker.database.Holding at 0x116f04c20>]},
 UUID('7509fde2-c757-486d-9b53-90f28b5d5a0c'): {'portfolio': <worker.database.Portfolio at 0x116eedd10>,
  'holdings': [<worker.database.Holding at 0x116f052b0>]},
 UUID('6c5d5b6e-f50a-40fe-ba5e-b208e1ecb458'): {'portfolio': <worker.database.Portfolio at 0x116e7a520>,
  'holdings': [<worker.database.Holding at 0x116f05240>]},
 UUID('24d4e3a0-5ea6-4ace-b18a-8ac9a16fcb8e'): {'portfolio': <worker.database.Portfolio at 0x116e7a2c0>,
  'holdings': [<worker.database.Holding at 0x116f05320>]},
 UUID('2b8e2f4b-c492-4521-89f3-0a4f8a2afcb1'): {'portfolio': <worker.database.Portfolio at 0x116f34cb0>,
  'holdings': [<worker.database.Holding at 0x116f05390>]},
 UUID('6528a25b-f12e-43aa-8d14-7faa56f71278'): {'portfolio': <worker.database.Portfolio at 0x1166ba470>,
  'holdings': [<worker.database.Holding at 0x116f05400>]},
 UUID('02105032-08f7-48b5-92f2-a4fdf3f81840'): {'portfolio': <worker.database.Portfolio at 0x1166ba250>,
  'holdings': [<worker.database.Holding at 0x116f05470>]},
 UUID('6e29d09a-5559-40ec-b473-0dee1315db94'): {'portfolio': <worker.database.Portfolio at 0x116ef9750>,
  'holdings': [<worker.database.Holding at 0x116f054e0>]},
 UUID('9c41728b-c00f-4d4c-8c53-44d0fcb00c6d'): {'portfolio': <worker.database.Portfolio at 0x116ef9450>,
  'holdings': [<worker.database.Holding at 0x116f05550>]},
 UUID('041e4244-f4c9-4699-bfce-81cf527d3711'): {'portfolio': <worker.database.Portfolio at 0x116f40230>,
  'holdings': [<worker.database.Holding at 0x116f055c0>]},
 UUID('a6185e5b-14af-4d3e-a496-34bf80dd26b2'): {'portfolio': <worker.database.Portfolio at 0x116f40140>,
  'holdings': [<worker.database.Holding at 0x116f056a0>]},
 UUID('faffb1de-06f3-47f1-92ad-ec27796b807f'): {'portfolio': <worker.database.Portfolio at 0x116f318d0>,
  'holdings': [<worker.database.Holding at 0x116f05630>]},
 UUID('74b13d77-71c9-4a5e-96cf-8e4b132de846'): {'portfolio': <worker.database.Portfolio at 0x116f31b70>,
  'holdings': [<worker.database.Holding at 0x116f05860>]},
 UUID('b2b57150-bc42-4948-9465-8c8de933f75f'): {'portfolio': <worker.database.Portfolio at 0x116f20d50>,
  'holdings': [<worker.database.Holding at 0x116f05710>]},
 UUID('2d92f54c-9f14-44e8-911c-674587f60d82'): {'portfolio': <worker.database.Portfolio at 0x1168cfad0>,
  'holdings': [<worker.database.Holding at 0x116f05780>]},
 UUID('b1a2abbb-47a3-489d-9abf-37c526a3d1a3'): {'portfolio': <worker.database.Portfolio at 0x1168cf950>,
  'holdings': [<worker.database.Holding at 0x116f059b0>]},
 UUID('e378decf-5e75-4b4a-ae58-cbf08243f787'): {'portfolio': <worker.database.Portfolio at 0x116e999c0>,
  'holdings': [<worker.database.Holding at 0x116f057f0>]},
 UUID('3f27a2f5-bad2-4f1a-8a9b-22995ac8fc07'): {'portfolio': <worker.database.Portfolio at 0x116e99860>,
  'holdings': [<worker.database.Holding at 0x116f058d0>]},
 UUID('2271ba74-4caa-42ac-8a2e-c39dd5dbb4f3'): {'portfolio': <worker.database.Portfolio at 0x116ef7750>,
  'holdings': [<worker.database.Holding at 0x116f05940>]},
 UUID('cfd71fcd-02ac-4bfe-a5d7-0a632bd2f9eb'): {'portfolio': <worker.database.Portfolio at 0x116ef7390>,
  'holdings': [<worker.database.Holding at 0x116f05a90>]},
 UUID('2e3c9fe5-2b23-4c8f-81f1-0b380627ccd5'): {'portfolio': <worker.database.Portfolio at 0x116e5e960>,
  'holdings': [<worker.database.Holding at 0x116f05a20>]},
 UUID('028b87b1-69ed-453e-8c54-b9d31a736543'): {'portfolio': <worker.database.Portfolio at 0x116f444d0>,
  'holdings': [<worker.database.Holding at 0x116f05b00>]},
 UUID('f9cc04e2-a614-4e70-acfd-8e23fa37af3c'): {'portfolio': <worker.database.Portfolio at 0x116f44550>,
  'holdings': [<worker.database.Holding at 0x116f05b70>]},
 UUID('dfa5835d-7c8a-4717-bd85-30716bd41335'): {'portfolio': <worker.database.Portfolio at 0x116f06ac0>,
  'holdings': [<worker.database.Holding at 0x116f05be0>]},
 UUID('c70e0d18-8243-4e3e-a201-949425b76045'): {'portfolio': <worker.database.Portfolio at 0x116f06970>,
  'holdings': [<worker.database.Holding at 0x116f05c50>]},
 UUID('cb90f820-ba51-4ddf-8bbf-d54730cc3482'): {'portfolio': <worker.database.Portfolio at 0x116f06a50>,
  'holdings': [<worker.database.Holding at 0x116f05cc0>]},
 UUID('f9721b67-94ce-420d-b770-556cfe883ad8'): {'portfolio': <worker.database.Portfolio at 0x116f06900>,
  'holdings': [<worker.database.Holding at 0x116f05d30>]},
 UUID('5f6154be-2628-470d-acef-eb8e6815980b'): {'portfolio': <worker.database.Portfolio at 0x116f06b30>,
  'holdings': [<worker.database.Holding at 0x116f05da0>]},
 UUID('86399e25-3954-47eb-bd33-91214ac7aa8a'): {'portfolio': <worker.database.Portfolio at 0x116f06ba0>,
  'holdings': [<worker.database.Holding at 0x116f05e10>]},
 UUID('65bd0c90-941b-4ff5-bafd-30ab87c5f539'): {'portfolio': <worker.database.Portfolio at 0x116f06c10>,
  'holdings': [<worker.database.Holding at 0x116f05e80>]},
 UUID('96b836c3-8679-4bda-b749-7c3c785ccd99'): {'portfolio': <worker.database.Portfolio at 0x116f06c80>,
  'holdings': [<worker.database.Holding at 0x116f05ef0>]},
 UUID('e541119f-ee43-4d52-a70c-e1d7765ec4e2'): {'portfolio': <worker.database.Portfolio at 0x116f06cf0>,
  'holdings': [<worker.database.Holding at 0x116f05f60>]},
 UUID('2eadb74c-b1e5-4763-8c10-e4c5c4a7a483'): {'portfolio': <worker.database.Portfolio at 0x116f06d60>,
  'holdings': [<worker.database.Holding at 0x116f05fd0>]},
 UUID('51fe62ab-38ea-4626-8ed0-3acc6b441cc7'): {'portfolio': <worker.database.Portfolio at 0x116f06dd0>,
  'holdings': [<worker.database.Holding at 0x116f06040>]},
 UUID('2b703602-f3f0-42a1-97f7-cb7e9a0ab92b'): {'portfolio': <worker.database.Portfolio at 0x116f06e40>,
  'holdings': [<worker.database.Holding at 0x116f060b0>]},
 UUID('f880bc04-e033-42f2-85dd-4be73588ceba'): {'portfolio': <worker.database.Portfolio at 0x116f06eb0>,
  'holdings': [<worker.database.Holding at 0x116f06120>]},
 UUID('1e28aa46-048c-42e1-a098-49cf4de0ebe3'): {'portfolio': <worker.database.Portfolio at 0x116f06f20>,
  'holdings': [<worker.database.Holding at 0x116f06190>]},
 UUID('44bdfc21-1e6f-461d-8f96-7167be1dc543'): {'portfolio': <worker.database.Portfolio at 0x116f07000>,
  'holdings': [<worker.database.Holding at 0x116f06200>]},
 UUID('e775f64e-fd39-4ed1-bc78-37f440f00e7a'): {'portfolio': <worker.database.Portfolio at 0x116f06f90>,
  'holdings': [<worker.database.Holding at 0x116f06270>]},
 UUID('539128a9-170c-42f5-94bc-f9b4f1cd2956'): {'portfolio': <worker.database.Portfolio at 0x116f070e0>,
  'holdings': [<worker.database.Holding at 0x116f062e0>]},
 UUID('502f0588-e1f3-4df9-b202-87c6e8af26ec'): {'portfolio': <worker.database.Portfolio at 0x116f07070>,
  'holdings': [<worker.database.Holding at 0x116f06350>]},
 UUID('e130aaea-4aec-4f7b-8a98-e79b344ef35c'): {'portfolio': <worker.database.Portfolio at 0x116f07150>,
  'holdings': [<worker.database.Holding at 0x116f06430>]},
 UUID('f38a52f5-a563-4cf4-b768-a64c5026ce5d'): {'portfolio': <worker.database.Portfolio at 0x116f071c0>,
  'holdings': [<worker.database.Holding at 0x116f063c0>]},
 UUID('d941b6be-8ce3-4b06-9e93-fa105153a697'): {'portfolio': <worker.database.Portfolio at 0x116f07230>,
  'holdings': [<worker.database.Holding at 0x116f06510>]},
 UUID('80742dfc-60e4-45f8-85fe-0c781d070466'): {'portfolio': <worker.database.Portfolio at 0x116f072a0>,
  'holdings': [<worker.database.Holding at 0x116f064a0>]},
 UUID('45a0aba3-aa87-41bd-8e0c-79540a2cb155'): {'portfolio': <worker.database.Portfolio at 0x116f07310>,
  'holdings': [<worker.database.Holding at 0x116f06580>]},
 UUID('ebc54cae-5121-4abb-b6a3-319e53a289d5'): {'portfolio': <worker.database.Portfolio at 0x116f07380>,
  'holdings': [<worker.database.Holding at 0x116f065f0>]},
 UUID('15cf150e-4108-4f5d-85f0-ddf047128e1d'): {'portfolio': <worker.database.Portfolio at 0x116f073f0>,
  'holdings': [<worker.database.Holding at 0x116f06660>]},
 UUID('441ee929-280d-41c8-af05-4b46d6ed293c'): {'portfolio': <worker.database.Portfolio at 0x116f07460>,
  'holdings': [<worker.database.Holding at 0x116f06740>]}}