In [6]:
import datetime
import polars as pl
from worker.database import connect
import json


DATE_END = datetime.date(2025, 6, 30)
DATE_START = datetime.date(1990, 1, 1)

In [ ]:


with connect() as db:
    df_portfolios = pl.read_database("SELECT * FROM portfolios", db)
    df_investments = pl.read_database(
        """
        SELECT 
            portfolio_id::TEXT as portfolio_id,
            instrument_id::TEXT as instrument_id,
            date,
            quantity
        FROM investments WHERE date <= :date
        """,
        db,
        execute_options={"params": {"date": DATE_END}},
    )

    df_all_dates = pl.DataFrame({"date": s_cal_dates})

    df_market_data = pl.read_database(
        """
            SELECT
                date,
                instrument_id::TEXT as instrument_id,
                value
            FROM market_data
            WHERE date <= :date_max 
            AND date >= :date_min 
            AND data_type = 'adj_close'""",
        db,
        execute_options={"params": {"date_min": DATE_START, "date_max": DATE_END}},
    )

# Build portfolio compositions and values for a range of dates
pairs = df_investments.select("portfolio_id", "instrument_id").unique()

dfs = []
for portfolio_id, instrument_id in pairs.iter_rows():
    df = (
        pl.DataFrame({"portfolio_id": portfolio_id, "instrument_id": instrument_id, "date": s_cal_dates})
        .join(df_investments, on=["portfolio_id", "instrument_id", "date"], how="left")
        .sort("date")
        .with_columns(quantity=pl.col("quantity").replace(None, 0).cum_sum())
        .filter((pl.col("quantity") != 0).cum_sum() > 0)
    )

    dfs.append(df)

df_all_ptf_compositions = pl.concat(dfs)

df_ptf_values = (
    df_all_ptf_compositions.filter(pl.col("date").dt.is_business_day())
    .join(df_market_data, on=["date", "instrument_id"], how="left")
    .group_by("portfolio_id", "instrument_id")
    .map_groups(lambda df: df.sort("date").with_columns(pl.col("value").forward_fill()))
    .filter(pl.col("value").is_not_null())
    .rename({"value": "price"})
    .with_columns(value=pl.col("quantity") * pl.col("price"))
)


# For a single date
df_positions_single_date = (
    df_investments.filter(pl.col("date") <= DATE_END)
    .group_by("portfolio_id", "instrument_id")
    .agg(quantity=pl.col("quantity").sum())
    .with_columns(date=pl.lit(DATE_END))
)

df_values_single_date = (
    df_positions_single_date.join(df_market_data, how="left", on=["instrument_id", "date"])
    .rename({"value": "price"})
    .with_columns(value=pl.col("quantity") * pl.col("price"))
)

u_ptfs = df_values_single_date["portfolio_id"].unique()

positions_json = {
    "date": DATE_END.strftime("%Y-%m-%d"),
    "data": {
        ptf: df_values_single_date.filter(pl.col("portfolio_id") == ptf)
        .drop("portfolio_id", "date", "price")
        .with_columns(pl.selectors.decimal().cast(pl.Float64))
        .to_dicts()
        for ptf in u_ptfs
    },
}

with open("ptfs.json", "w") as fd:
    json.dump(positions_json, fd)

In [15]:
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from worker.database import Base, PortfolioComposition, PortfolioValue

def _insert_list_of_dicts(items: list[dict], table: type[Base], session: Session):
    chunk_size = 1000
    total_inserted = 0
    
    for i in range(0, len(items), chunk_size):
        chunk = items[i:i+chunk_size]
        
        try:
            stmt = insert(table).values(chunk)
            stmt = stmt.on_conflict_do_nothing()
            result = session.execute(stmt)
            session.commit()
            
            chunk_inserted = result.rowcount
            total_inserted += chunk_inserted
            
            print(f"Chunk {i//chunk_size + 1}: Inserted {chunk_inserted}/{len(chunk)} rows (Total: {total_inserted})")
            
        except Exception as e:
            print(f"Error inserting chunk {i//chunk_size + 1}: {e}")
            session.rollback()
                        

def fill_portfolio_positions_for_single_date(session, date: datetime.date):
    df_investments = pl.read_database(
        """
        SELECT 
            portfolio_id::TEXT as portfolio_id,
            instrument_id::TEXT as instrument_id,
            date,
            quantity
        FROM investments WHERE date <= :date
        """,
        session,
        execute_options={"params": {"date": DATE_END}},
    )
    
    df_positions_single_date = (
        df_investments.filter(pl.col("date") <= DATE_END)
        .group_by("portfolio_id", "instrument_id")
        .agg(quantity=pl.col("quantity").sum())
        .with_columns(date=pl.lit(DATE_END))
    )

    _insert_list_of_dicts(items=df_positions_single_date.to_dicts(), table=PortfolioComposition, session=session)


    session.commit()

def fill_portfolio_values_multiple_dates(session, date_start: datetime.date, date_end: datetime.date):
    s_cal_dates = pl.date_range(date_start, date_end, eager=True)

    df_investments = pl.read_database(
        """
        SELECT 
            portfolio_id::TEXT as portfolio_id,
            instrument_id::TEXT as instrument_id,
            date,
            quantity
        FROM investments WHERE date <= :date
        """,
        db,
        execute_options={"params": {"date": DATE_END}},
    )

    df_market_data = pl.read_database(
        """
            SELECT
                date,
                instrument_id::TEXT as instrument_id,
                value
            FROM market_data
            WHERE date <= :date_max 
            AND date >= :date_min 
            AND data_type = 'adj_close'""",
        db,
        execute_options={"params": {"date_min": date_start, "date_max": date_end}},
    )

    # Build portfolio compositions and values for a range of dates
    pairs = df_investments.select("portfolio_id", "instrument_id").unique()

    dfs = []
    for portfolio_id, instrument_id in pairs.iter_rows():
        df = (
            pl.DataFrame({"portfolio_id": portfolio_id, "instrument_id": instrument_id, "date": s_cal_dates})
            .join(df_investments, on=["portfolio_id", "instrument_id", "date"], how="left")
            .sort("date")
            .with_columns(quantity=pl.col("quantity").replace(None, 0).cum_sum())
            .filter((pl.col("quantity") != 0).cum_sum() > 0)
        )

        dfs.append(df)

    df_all_ptf_compositions = pl.concat(dfs)

    df_ptf_values = (
        df_all_ptf_compositions.filter(pl.col("date").dt.is_business_day())
        .join(df_market_data, on=["date", "instrument_id"], how="left")
        .group_by("portfolio_id", "instrument_id")
        .map_groups(lambda df: df.sort("date").with_columns(pl.col("value").forward_fill()))
        .filter(pl.col("value").is_not_null())
        .rename({"value": "price"})
        .with_columns(value=pl.col("quantity") * pl.col("price"))
        .group_by("portfolio_id", "date")
        .agg(value=pl.col("value").sum())
    )

    _insert_list_of_dicts(items=df_ptf_values.to_dicts(), table=PortfolioValue, session=session)

    return df_ptf_values

In [21]:
with connect() as session:
    fill_portfolio_positions_for_single_date(session, date=DATE_END)

Chunk 1: Inserted 0/50 rows (Total: 0)

In [151]:
with connect() as session:
    out = fill_portfolio_values_multiple_dates(session, date_start=DATE_START, date_end=DATE_END)

out

Chunk 1: Inserted 0/1000 rows (Total: 0)
Chunk 2: Inserted 0/1000 rows (Total: 0)
Chunk 3: Inserted 0/1000 rows (Total: 0)
Chunk 4: Inserted 0/1000 rows (Total: 0)
Chunk 5: Inserted 0/1000 rows (Total: 0)
Chunk 6: Inserted 0/1000 rows (Total: 0)
Chunk 7: Inserted 0/1000 rows (Total: 0)
Chunk 8: Inserted 0/1000 rows (Total: 0)
Chunk 9: Inserted 0/1000 rows (Total: 0)
Chunk 10: Inserted 0/1000 rows (Total: 0)
Chunk 11: Inserted 0/1000 rows (Total: 0)
Chunk 12: Inserted 0/1000 rows (Total: 0)
Chunk 13: Inserted 0/1000 rows (Total: 0)
Chunk 14: Inserted 0/1000 rows (Total: 0)
Chunk 15: Inserted 0/1000 rows (Total: 0)
Chunk 16: Inserted 0/1000 rows (Total: 0)
Chunk 17: Inserted 0/1000 rows (Total: 0)
Chunk 18: Inserted 0/1000 rows (Total: 0)
Chunk 19: Inserted 0/1000 rows (Total: 0)
Chunk 20: Inserted 0/1000 rows (Total: 0)
Chunk 21: Inserted 0/1000 rows (Total: 0)
Chunk 22: Inserted 0/1000 rows (Total: 0)
Chunk 23: Inserted 0/1000 rows (Total: 0)
Chunk 24: Inserted 0/1000 rows (Total: 0)
Chunk 25: Inserted 0/1000 rows (Total: 0)
Chunk 26: Inserted 0/1000 rows (Total: 0)
Chunk 27: Inserted 0/1000 rows (Total: 0)
Chunk 28: Inserted 0/1000 rows (Total: 0)
Chunk 29: Inserted 0/1000 rows (Total: 0)
Chunk 30: Inserted 0/1000 rows (Total: 0)
Chunk 31: Inserted 0/1000 rows (Total: 0)
Chunk 32: Inserted 0/1000 rows (Total: 0)
Chunk 33: Inserted 0/1000 rows (Total: 0)
Chunk 34: Inserted 0/1000 rows (Total: 0)
Chunk 35: Inserted 0/1000 rows (Total: 0)
Chunk 36: Inserted 0/1000 rows (Total: 0)
Chunk 37: Inserted 0/1000 rows (Total: 0)
Chunk 38: Inserted 0/1000 rows (Total: 0)
Chunk 39: Inserted 0/1000 rows (Total: 0)
Chunk 40: Inserted 0/1000 rows (Total: 0)
Chunk 41: Inserted 0/1000 rows (Total: 0)
Chunk 42: Inserted 0/1000 rows (Total: 0)
Chunk 43: Inserted 0/1000 rows (Total: 0)
Chunk 44: Inserted 0/1000 rows (Total: 0)
Chunk 45: Inserted 0/1000 rows (Total: 0)
Chunk 46: Inserted 0/1000 rows (Total: 0)
Chunk 47: Inserted 0/1000 rows (Total: 0)
Chunk 48: Inserted 0/1000 rows (Total: 0)
Chunk 49: Inserted 0/1000 rows (Total: 0)
Chunk 50: Inserted 0/1000 rows (Total: 0)
Chunk 51: Inserted 0/1000 rows (Total: 0)
Chunk 52: Inserted 0/1000 rows (Total: 0)
Chunk 53: Inserted 0/1000 rows (Total: 0)
Chunk 54: Inserted 0/1000 rows (Total: 0)
Chunk 55: Inserted 0/1000 rows (Total: 0)
Chunk 56: Inserted 0/1000 rows (Total: 0)
Chunk 57: Inserted 0/1000 rows (Total: 0)
Chunk 58: Inserted 0/1000 rows (Total: 0)
Chunk 59: Inserted 0/1000 rows (Total: 0)
Chunk 60: Inserted 0/1000 rows (Total: 0)
Chunk 61: Inserted 0/1000 rows (Total: 0)
Chunk 62: Inserted 0/1000 rows (Total: 0)
Chunk 63: Inserted 0/1000 rows (Total: 0)
Chunk 64: Inserted 0/1000 rows (Total: 0)
Chunk 65: Inserted 0/1000 rows (Total: 0)
Chunk 66: Inserted 0/1000 rows (Total: 0)
Chunk 67: Inserted 0/1000 rows (Total: 0)
Chunk 68: Inserted 0/1000 rows (Total: 0)
Chunk 69: Inserted 0/1000 rows (Total: 0)
Chunk 70: Inserted 0/1000 rows (Total: 0)
Chunk 71: Inserted 0/1000 rows (Total: 0)
Chunk 72: Inserted 0/1000 rows (Total: 0)
Chunk 73: Inserted 0/1000 rows (Total: 0)
Chunk 74: Inserted 0/1000 rows (Total: 0)
Chunk 75: Inserted 0/1000 rows (Total: 0)
Chunk 76: Inserted 0/1000 rows (Total: 0)
Chunk 77: Inserted 0/1000 rows (Total: 0)
Chunk 78: Inserted 0/1000 rows (Total: 0)
Chunk 79: Inserted 0/1000 rows (Total: 0)
Chunk 80: Inserted 0/1000 rows (Total: 0)
Chunk 81: Inserted 0/1000 rows (Total: 0)
Chunk 82: Inserted 0/1000 rows (Total: 0)
Chunk 83: Inserted 0/1000 rows (Total: 0)
Chunk 84: Inserted 0/1000 rows (Total: 0)
Chunk 85: Inserted 0/1000 rows (Total: 0)
Chunk 86: Inserted 0/1000 rows (Total: 0)
Chunk 87: Inserted 0/1000 rows (Total: 0)
Chunk 88: Inserted 0/1000 rows (Total: 0)
Chunk 89: Inserted 0/1000 rows (Total: 0)
Chunk 90: Inserted 0/1000 rows (Total: 0)
Chunk 91: Inserted 0/1000 rows (Total: 0)
Chunk 92: Inserted 0/1000 rows (Total: 0)
Chunk 93: Inserted 0/1000 rows (Total: 0)
Chunk 94: Inserted 0/1000 rows (Total: 0)
Chunk 95: Inserted 0/1000 rows (Total: 0)
Chunk 96: Inserted 0/1000 rows (Total: 0)
Chunk 97: Inserted 0/1000 rows (Total: 0)
Chunk 98: Inserted 0/1000 rows (Total: 0)
Chunk 99: Inserted 0/1000 rows (Total: 0)
Chunk 100: Inserted 0/1000 rows (Total: 0)
Chunk 101: Inserted 0/1000 rows (Total: 0)
Chunk 102: Inserted 0/1000 rows (Total: 0)
Chunk 103: Inserted 0/1000 rows (Total: 0)
Chunk 104: Inserted 0/1000 rows (Total: 0)
Chunk 105: Inserted 0/1000 rows (Total: 0)
Chunk 106: Inserted 0/1000 rows (Total: 0)
Chunk 107: Inserted 0/1000 rows (Total: 0)
Chunk 108: Inserted 0/1000 rows (Total: 0)
Chunk 109: Inserted 0/1000 rows (Total: 0)
Chunk 110: Inserted 0/1000 rows (Total: 0)
Chunk 111: Inserted 0/1000 rows (Total: 0)
Chunk 112: Inserted 0/1000 rows (Total: 0)
Chunk 113: Inserted 0/1000 rows (Total: 0)
Chunk 114: Inserted 0/1000 rows (Total: 0)
Chunk 115: Inserted 0/1000 rows (Total: 0)
Chunk 116: Inserted 0/1000 rows (Total: 0)
Chunk 117: Inserted 0/1000 rows (Total: 0)
Chunk 118: Inserted 0/1000 rows (Total: 0)
Chunk 119: Inserted 0/1000 rows (Total: 0)
Chunk 120: Inserted 0/1000 rows (Total: 0)
Chunk 121: Inserted 0/1000 rows (Total: 0)
Chunk 122: Inserted 0/1000 rows (Total: 0)
Chunk 123: Inserted 0/1000 rows (Total: 0)
Chunk 124: Inserted 0/1000 rows (Total: 0)
Chunk 125: Inserted 0/1000 rows (Total: 0)
Chunk 126: Inserted 0/97 rows (Total: 0)

shape: (125_097, 3)
┌─────────────────────────────────┬────────────┬────────────────────────────┐
│ portfolio_id                    ┆ date       ┆ value                      │
│ ---                             ┆ ---        ┆ ---                        │
│ str                             ┆ date       ┆ decimal[*,20]              │
╞═════════════════════════════════╪════════════╪════════════════════════════╡
│ b56a59f5-0e5d-4e2c-92cd-61236f… ┆ 2016-03-16 ┆ 45964.37673380000000000000 │
│ 3a844f39-4f69-452c-a4c1-d988e2… ┆ 2023-11-13 ┆ 76290.00000000000000000000 │
│ 67756108-d9ee-44e0-ac13-0e133d… ┆ 2024-06-18 ┆ 81090.00000000000000000000 │
│ 73b9f260-1100-469b-99a2-3a5f9e… ┆ 2017-01-05 ┆ 69774.59589230000000000000 │
│ d7da851b-20c5-4de0-9c93-68a9f1… ┆ 2021-03-18 ┆ 64490.00000000000000000000 │
│ …                               ┆ …          ┆ …                          │
│ 8916932a-fe16-49e1-86b7-e99113… ┆ 2023-03-28 ┆ 42000.00000000000000000000 │
│ f5764652-eca7-48f2-b621-b5fdff… ┆ 2018-11-09 ┆ 41383.38413340000000000000 │
│ 7bb42e63-eb49-4855-8aec-af08df… ┆ 2025-01-27 ┆ 44810.00000000000000000000 │
│ a2d06bf1-3dd4-4293-87a6-62cd3a… ┆ 2020-12-30 ┆ 31530.00000000000000000000 │
│ 0b209d5c-12ed-48af-a597-b1e22f… ┆ 2018-05-24 ┆ 43731.83230980000000000000 │
└─────────────────────────────────┴────────────┴────────────────────────────┘

In [128]:
positions_json

{'date': datetime.date(2025, 6, 30),
 'data': {'00e01b8c-84f4-4a73-9345-ed2ad74b96b2': [{'instrument_id': '50d64c2b-1484-41db-8095-d18e20c5f436',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('55680.00000000000000000000')}],
  'f5764652-eca7-48f2-b621-b5fdff1de41f': [{'instrument_id': '29fcfd80-cc50-483f-b2f1-a7099277e15a',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('61570.00000000000000000000')}],
  '021c0c4c-f691-45d3-ba82-f2b3a650dff8': [{'instrument_id': 'a42d14ef-4680-4d48-ae4e-c6f753cc2ee1',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('46310.00000000000000000000')}],
  '73b9f260-1100-469b-99a2-3a5f9e64ed92': [{'instrument_id': '56cfb131-8c13-4e90-a0e9-55f93ece20d1',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('94770.00000000000000000000')}],
  '67756108-d9ee-44e0-ac13-0e133d3e39c0': [{'instrument_id': '07602a17-b596-47d1-adc2-bda6d3cda617',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('77180.00000000000000000000')}],
  '4daf79fe-feb9-4c5a-ba1f-a67b965c679a': [{'instrument_id': '6c125ed4-4a90-41c4-b389-226eb7e93b07',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('88250.00000000000000000000')}],
  '7980bbb5-f4e8-43d5-a0a8-2cde41aa8781': [{'instrument_id': '7edd1534-ecb5-4a73-a3b0-4bcfe6edc0e1',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('67780.00000000000000000000')}],
  '1d08e7c8-f73c-4e6a-98ff-639871fb4cf8': [{'instrument_id': '5817580d-febb-47d3-a1dd-70cae7d5d45f',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('24700.00000000000000000000')}],
  '74623cfa-69a7-43c4-a6e5-3beb9b5e401b': [{'instrument_id': '35a6016b-daf4-40a4-84d1-c5492ae12d0c',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('67120.00000000000000000000')}],
  'e01b0257-f0ea-40a3-b91d-434677798cec': [{'instrument_id': '45063710-ef21-46d9-9cc7-beaad4766e7b',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('51090.00000000000000000000')}],
  '267b92c2-aa8a-49fe-bf5c-9a2d2cc74924': [{'instrument_id': 'c6d94933-a248-4df5-a56e-b2c0c08fe450',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('104480.00000000000000000000')}],
  '7bb42e63-eb49-4855-8aec-af08df5f16ee': [{'instrument_id': 'e24878f5-b374-4d80-ba37-234362ea1ec9',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('45440.00000000000000000000')}],
  '6f7e34d1-0109-4f9e-8aa0-5d4e5f6721e2': [{'instrument_id': '8cdd951a-8d3d-40bb-aa43-761fb1226d81',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('36760.00000000000000000000')}],
  '52f40e28-a1bb-443a-81ff-de92de67dd7d': [{'instrument_id': 'b784bce9-a223-49a4-9c09-9f381cabaf04',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('89390.00000000000000000000')}],
  'e3a50d76-dcb7-4377-8ad3-8ff9f442752d': [{'instrument_id': 'fb39c249-6cb1-47b6-9220-6c0f8daac13a',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('26210.00000000000000000000')}],
  '55510bc4-da2e-43ec-a304-a9d080861be4': [{'instrument_id': '1ca5977c-2cd8-48bc-983f-681412c0d309',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('68700.00000000000000000000')}],
  'd36a08ce-9974-4a76-a6bb-7cf37fc22dfa': [{'instrument_id': '3c61196e-5014-4a5d-87b8-9b413c9de878',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('135040.00000000000000000000')}],
  'ce6f327b-247e-4a50-9352-66bc437f6f7b': [{'instrument_id': '3c7f3c30-4848-48ce-b2a5-3fc1b9e31b1e',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('37510.00000000000000000000')}],
  'bab4b781-3003-427b-8985-cef95d3dd87e': [{'instrument_id': '1fa0820d-a943-4d8a-8394-adafc9bb81cd',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('38970.00000000000000000000')}],
  'a2d06bf1-3dd4-4293-87a6-62cd3aade349': [{'instrument_id': 'fd9f21e1-80be-478c-9fd4-fe1d5011d962',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('38540.00000000000000000000')}],
  'c681d170-805f-43f4-928b-86e1aa273753': [{'instrument_id': '8da68d05-90e7-47c9-a779-05fce4a165ee',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('13260.00000000000000000000')}],
  '48164b2c-2eca-4d1e-81c7-f8c8115745d5': [{'instrument_id': 'b2409b2e-2e42-4c6e-8bc5-0b74aea21798',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('81060.00000000000000000000')}],
  'd7da851b-20c5-4de0-9c93-68a9f16fb55e': [{'instrument_id': '02f2fb63-27d1-43bf-953d-7249c482b082',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('60030.00000000000000000000')}],
  'f0085a41-9c45-4bd5-8a9b-456a3115f72b': [{'instrument_id': '727b0b7c-268d-42c4-bb48-11020f53958a',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('59450.00000000000000000000')}],
  '3a844f39-4f69-452c-a4c1-d988e27819ee': [{'instrument_id': '0e98f7d8-5fe7-4de8-a8a3-46c342374abe',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('107810.00000000000000000000')}],
  'ca366c28-aff3-45f6-ae3b-37079cdc445c': [{'instrument_id': '6444a8ec-8304-4918-a36d-0766727c57d7',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('424580.00000000000000000000')}],
  'f4dd8467-36cf-4d10-93d3-a0699ae8eb70': [{'instrument_id': 'c135cb6f-2a23-4032-ae80-856a310752a8',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('74970.00000000000000000000')}],
  '23ad6712-e7e8-4db5-9999-bca22e4dbd2b': [{'instrument_id': '588cf2ec-8e51-4360-8d55-8c807abd11c8',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('99200.00000000000000000000')}],
  '19008197-3f49-42f3-a057-63a0be83ee71': [{'instrument_id': 'fe4ea713-6883-489f-bd81-8b3e1edaa46f',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('43100.00000000000000000000')}],
  'b872c12a-2db2-4898-a52d-4f09e8254dba': [{'instrument_id': '27fb9e0c-145d-400a-aa73-1057ff3cb314',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('72680.00000000000000000000')}],
  '0a501045-acfb-41c3-ba19-e64d56093543': [{'instrument_id': '71b05bd8-7aa9-4785-9e99-16dc7a4ebca1',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('62020.00000000000000000000')}],
  '78e37b84-0a65-4f70-a706-ae017593868a': [{'instrument_id': '39a5e158-c52e-447d-a20e-180129350767',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('109290.00000000000000000000')}],
  'da0955b6-52f2-4c70-bd60-e3a3794d42dc': [{'instrument_id': 'bc594e1a-e7b2-4b5f-bf6d-e53283bb2d0f',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('28850.00000000000000000000')}],
  'fe1ab00b-670a-44e8-bd02-71b5ef304613': [{'instrument_id': '49f41541-e632-46f4-bb42-7cbfaf0b0fe9',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('66200.00000000000000000000')}],
  '925a0ff5-3258-44c4-86eb-3de00c23066a': [{'instrument_id': 'b943b709-b920-44a1-a0c2-c056b667ef98',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('22040.00000000000000000000')}],
  '16cc08b3-c767-464d-8d9c-573d4d80c57d': [{'instrument_id': '5ce44cf1-fbc8-4224-b693-db704e6fae0c',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('620900.00000000000000000000')}],
  'cdbad104-f1fb-4ca9-9360-a4e865520710': [{'instrument_id': '491f4737-7acc-4f1a-b486-e6cc014c5e76',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('110040.00000000000000000000')}],
  'eec40028-ed16-4b8c-8d96-72e70d5158f4': [{'instrument_id': '29cec4b9-c146-4ff8-a725-5cf20bea7fef',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('62360.00000000000000000000')}],
  '64ae58df-139d-4425-a307-05072edfc484': [{'instrument_id': '929e3e08-574e-4b80-ab1d-57bdef534444',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('64850.00000000000000000000')}],
  '4ff1baf0-73ed-4345-9805-eb35a9a7b318': [{'instrument_id': 'f48b1e9f-e2d6-442a-acf6-2ba36202a71c',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('83480.00000000000000000000')}],
  'ea60a615-6c56-4c4c-936f-6727f641fd89': [{'instrument_id': '70e9623b-1ea8-4de7-a8eb-4193d4fc1302',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('17630.00000000000000000000')}],
  '0b209d5c-12ed-48af-a597-b1e22f7780b6': [{'instrument_id': '41712141-41c4-4e22-83d1-8cc45c44fff1',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('48240.00000000000000000000')}],
  '2c6a78e0-86dc-4ad1-9cf7-a4a5f6348c09': [{'instrument_id': 'c8c98404-6e77-4667-8a5c-c25da42654e1',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('60560.00000000000000000000')}],
  '8916932a-fe16-49e1-86b7-e99113a63df1': [{'instrument_id': 'a421b6cb-056c-42eb-96ba-c85c8f35e654',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('53750.00000000000000000000')}],
  'ea975ea7-5bc4-4584-ad79-ea24d16d2b21': [{'instrument_id': 'cdf36a61-82d3-4b48-b581-6d77990bd275',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('32260.00000000000000000000')}],
  '594e712e-88b9-4bd8-ae5e-0ea97fca8af4': [{'instrument_id': '455dda36-171f-4412-baf4-3674c6e3ece8',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('84890.00000000000000000000')}],
  'a9ed8979-b384-46f9-a1d8-71fce6a4c371': [{'instrument_id': '22440153-44ce-4830-a6b1-1d7232e0c479',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('109610.00000000000000000000')}],
  '0693a3b1-74d0-4a6d-aca0-68e05e949d72': [{'instrument_id': 'b4dc9f2c-b477-415f-91a8-36ddf62043e4',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('92620.00000000000000000000')}],
  'b56a59f5-0e5d-4e2c-92cd-61236fb92c8a': [{'instrument_id': '559e6146-595c-4ea6-a489-0415f41911c3',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('48720.00000000000000000000')}],
  '0b56cedc-5e07-4f8e-b6bf-b25a195b2786': [{'instrument_id': '86e48142-757b-4e0d-8f90-f7d70b0445ae',
    'quantity': Decimal('1000.00000000'),
    'value': Decimal('93890.00000000000000000000')}]}}

In [122]:
df_ptf_values.filter(pl.col("date") == DATE_END)

shape: (50, 6)
┌─────────────────┬─────────────────┬────────────┬───────────────┬────────────────┬────────────────┐
│ portfolio_id    ┆ instrument_id   ┆ date       ┆ quantity      ┆ price          ┆ value          │
│ ---             ┆ ---             ┆ ---        ┆ ---           ┆ ---            ┆ ---            │
│ str             ┆ str             ┆ date       ┆ decimal[*,8]  ┆ decimal[*,10]  ┆ decimal[*,20]  │
╞═════════════════╪═════════════════╪════════════╪═══════════════╪════════════════╪════════════════╡
│ b56a59f5-0e5d-4 ┆ 559e6146-595c-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 48.7200000000  ┆ 48720.00000000 │
│ e2c-92cd-61236f ┆ ea6-a489-0415f4 ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ da0955b6-52f2-4 ┆ bc594e1a-e7b2-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 28.8500000000  ┆ 28850.00000000 │
│ c70-bd60-e3a379 ┆ b5f-bf6d-e53283 ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ 23ad6712-e7e8-4 ┆ 588cf2ec-8e51-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 99.2000000000  ┆ 99200.00000000 │
│ db5-9999-bca22e ┆ 360-8d55-8c807a ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ 267b92c2-aa8a-4 ┆ c6d94933-a248-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 104.4800000000 ┆ 104480.0000000 │
│ 9fe-bf5c-9a2d2c ┆ df5-a56e-b2c0c0 ┆            ┆               ┆                ┆ 0000000000000  │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ fe1ab00b-670a-4 ┆ 49f41541-e632-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 66.2000000000  ┆ 66200.00000000 │
│ 4e8-bd02-71b5ef ┆ 6f4-bb42-7cbfaf ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ …               ┆ …               ┆ …          ┆ …             ┆ …              ┆ …              │
│ d7da851b-20c5-4 ┆ 02f2fb63-27d1-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 60.0300000000  ┆ 60030.00000000 │
│ de0-9c93-68a9f1 ┆ 3bf-953d-7249c4 ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ 4daf79fe-feb9-4 ┆ 6c125ed4-4a90-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 88.2500000000  ┆ 88250.00000000 │
│ c5a-ba1f-a67b96 ┆ 1c4-b389-226eb7 ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ 48164b2c-2eca-4 ┆ b2409b2e-2e42-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 81.0600000000  ┆ 81060.00000000 │
│ d1e-81c7-f8c811 ┆ c6e-8bc5-0b74ae ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ 0693a3b1-74d0-4 ┆ b4dc9f2c-b477-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 92.6200000000  ┆ 92620.00000000 │
│ a6d-aca0-68e05e ┆ 15f-91a8-36ddf6 ┆            ┆               ┆                ┆ 000000000000   │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
│ a9ed8979-b384-4 ┆ 22440153-44ce-4 ┆ 2025-06-30 ┆ 1000.00000000 ┆ 109.6100000000 ┆ 109610.0000000 │
│ 6f9-a1d8-71fce6 ┆ 830-a6b1-1d7232 ┆            ┆               ┆                ┆ 0000000000000  │
│ …               ┆ …               ┆            ┆               ┆                ┆                │
└─────────────────┴─────────────────┴────────────┴───────────────┴────────────────┴────────────────┘

In [ ]:
df_values_single_date.drop("price", "quantity", "instrument_id").group_by("portfolio_id", "date").agg(
    value=pl.col("value").sum()
)

shape: (50, 3)
┌─────────────────────────────────┬────────────┬─────────────────────────────┐
│ portfolio_id                    ┆ date       ┆ value                       │
│ ---                             ┆ ---        ┆ ---                         │
│ str                             ┆ date       ┆ decimal[*,20]               │
╞═════════════════════════════════╪════════════╪═════════════════════════════╡
│ da0955b6-52f2-4c70-bd60-e3a379… ┆ 2025-06-30 ┆ 28850.00000000000000000000  │
│ 8916932a-fe16-49e1-86b7-e99113… ┆ 2025-06-30 ┆ 53750.00000000000000000000  │
│ 16cc08b3-c767-464d-8d9c-573d4d… ┆ 2025-06-30 ┆ 620900.00000000000000000000 │
│ d36a08ce-9974-4a76-a6bb-7cf37f… ┆ 2025-06-30 ┆ 135040.00000000000000000000 │
│ 7bb42e63-eb49-4855-8aec-af08df… ┆ 2025-06-30 ┆ 45440.00000000000000000000  │
│ …                               ┆ …          ┆ …                           │
│ 2c6a78e0-86dc-4ad1-9cf7-a4a5f6… ┆ 2025-06-30 ┆ 60560.00000000000000000000  │
│ 021c0c4c-f691-45d3-ba82-f2b3a6… ┆ 2025-06-30 ┆ 46310.00000000000000000000  │
│ b56a59f5-0e5d-4e2c-92cd-61236f… ┆ 2025-06-30 ┆ 48720.00000000000000000000  │
│ 0693a3b1-74d0-4a6d-aca0-68e05e… ┆ 2025-06-30 ┆ 92620.00000000000000000000  │
│ ea60a615-6c56-4c4c-936f-6727f6… ┆ 2025-06-30 ┆ 17630.00000000000000000000  │
└─────────────────────────────────┴────────────┴─────────────────────────────┘

In [99]:
df

shape: (12_965, 4)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┬───────────────┐
│ portfolio_id                    ┆ instrument_id                   ┆ date       ┆ quantity      │
│ ---                             ┆ ---                             ┆ ---        ┆ ---           │
│ str                             ┆ str                             ┆ date       ┆ decimal[*,8]  │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╪═══════════════╡
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 1990-01-01 ┆ 0.00000000    │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 1990-01-02 ┆ 0.00000000    │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 1990-01-03 ┆ 0.00000000    │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 1990-01-04 ┆ 0.00000000    │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 1990-01-05 ┆ 0.00000000    │
│ …                               ┆ …                               ┆ …          ┆ …             │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 2025-06-26 ┆ 1000.00000000 │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 2025-06-27 ┆ 1000.00000000 │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 2025-06-28 ┆ 1000.00000000 │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 2025-06-29 ┆ 1000.00000000 │
│ a9ed8979-b384-46f9-a1d8-71fce6… ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 2025-06-30 ┆ 1000.00000000 │
└─────────────────────────────────┴─────────────────────────────────┴────────────┴───────────────┘

In [87]:
len(pairs)

50

In [67]:
df_all_dates

shape: (12_965, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 1990-01-01 │
│ 1990-01-02 │
│ 1990-01-03 │
│ 1990-01-04 │
│ 1990-01-05 │
│ …          │
│ 2025-06-26 │
│ 2025-06-27 │
│ 2025-06-28 │
│ 2025-06-29 │
│ 2025-06-30 │
└────────────┘

In [47]:
df_investment_values

shape: (120_344, 5)
┌────────────┬─────────────────────────────────┬────────────────┬──────────────┬──────────────┐
│ date       ┆ instrument_id                   ┆ value          ┆ portfolio_id ┆ quantity     │
│ ---        ┆ ---                             ┆ ---            ┆ ---          ┆ ---          │
│ date       ┆ str                             ┆ decimal[*,10]  ┆ str          ┆ decimal[*,8] │
╞════════════╪═════════════════════════════════╪════════════════╪══════════════╪══════════════╡
│ 2018-01-30 ┆ 35a6016b-daf4-40a4-84d1-c5492a… ┆ 56.7850882744  ┆ null         ┆ 0.00000000   │
│ 2022-08-11 ┆ 22440153-44ce-4830-a6b1-1d7232… ┆ 112.9300000000 ┆ null         ┆ 0.00000000   │
│ 2018-01-17 ┆ 8da68d05-90e7-47c9-a779-05fce4… ┆ 15.9609769894  ┆ null         ┆ 0.00000000   │
│ 2020-10-23 ┆ cdf36a61-82d3-4b48-b581-6d7799… ┆ 15.6200000000  ┆ null         ┆ 0.00000000   │
│ 2016-01-29 ┆ b4dc9f2c-b477-415f-91a8-36ddf6… ┆ 85.5330980050  ┆ null         ┆ 0.00000000   │
│ …          ┆ …                               ┆ …              ┆ …            ┆ …            │
│ 2021-04-16 ┆ 588cf2ec-8e51-4360-8d55-8c807a… ┆ 114.5400000000 ┆ null         ┆ 0.00000000   │
│ 2021-03-16 ┆ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 136.3100000000 ┆ null         ┆ 0.00000000   │
│ 2017-12-06 ┆ 86e48142-757b-4e0d-8f90-f7d70b… ┆ 99.9295975801  ┆ null         ┆ 0.00000000   │
│ 2023-01-03 ┆ 29cec4b9-c146-4ff8-a725-5cf20b… ┆ 34.8800000000  ┆ null         ┆ 0.00000000   │
│ 2016-12-14 ┆ b784bce9-a223-49a4-9c09-9f381c… ┆ 51.9455392402  ┆ null         ┆ 0.00000000   │
└────────────┴─────────────────────────────────┴────────────────┴──────────────┴──────────────┘

In [29]:
df_investments

shape: (50, 1)
┌─────────────────────────────────┐
│ instrument_id                   │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ c6d94933-a248-4df5-a56e-b2c0c0… │
│ 56cfb131-8c13-4e90-a0e9-55f93e… │
│ f48b1e9f-e2d6-442a-acf6-2ba362… │
│ 559e6146-595c-4ea6-a489-0415f4… │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… │
│ …                               │
│ cdf36a61-82d3-4b48-b581-6d7799… │
│ 3c61196e-5014-4a5d-87b8-9b413c… │
│ 3c7f3c30-4848-48ce-b2a5-3fc1b9… │
│ b2409b2e-2e42-4c6e-8bc5-0b74ae… │
│ 29cec4b9-c146-4ff8-a725-5cf20b… │
└─────────────────────────────────┘

In [23]:
df_investments

shape: (50, 5)
┌────────────┬───────────────────────┬──────────────────────┬───────────────┬──────────────────────┐
│ date       ┆ portfolio_id          ┆ instrument_id        ┆ quantity      ┆ id                   │
│ ---        ┆ ---                   ┆ ---                  ┆ ---           ┆ ---                  │
│ date       ┆ object                ┆ object               ┆ decimal[*,8]  ┆ object               │
╞════════════╪═══════════════════════╪══════════════════════╪═══════════════╪══════════════════════╡
│ 2000-01-01 ┆ 267b92c2-aa8a-49fe-bf ┆ c6d94933-a248-4df5-a ┆ 1000.00000000 ┆ 997f3c00-b1fa-4537-b │
│            ┆ 5c-9a2d2c…            ┆ 56e-b2c0c0…          ┆               ┆ 247-e0b5b8…          │
│ 2000-01-01 ┆ 73b9f260-1100-469b-99 ┆ 56cfb131-8c13-4e90-a ┆ 1000.00000000 ┆ 656b13a9-cc85-4b75-a │
│            ┆ a2-3a5f9e…            ┆ 0e9-55f93e…          ┆               ┆ 533-c3abd9…          │
│ 2000-01-01 ┆ 4ff1baf0-73ed-4345-98 ┆ f48b1e9f-e2d6-442a-a ┆ 1000.00000000 ┆ 49d56add-5e02-46b8-a │
│            ┆ 05-eb35a9…            ┆ cf6-2ba362…          ┆               ┆ 664-183bae…          │
│ 2000-01-01 ┆ b56a59f5-0e5d-4e2c-92 ┆ 559e6146-595c-4ea6-a ┆ 1000.00000000 ┆ d4eb3878-8a20-4959-a │
│            ┆ cd-61236f…            ┆ 489-0415f4…          ┆               ┆ 220-702fb9…          │
│ 2000-01-01 ┆ 7980bbb5-f4e8-43d5-a0 ┆ 7edd1534-ecb5-4a73-a ┆ 1000.00000000 ┆ 3dca983e-6c7c-4eff-b │
│            ┆ a8-2cde41…            ┆ 3b0-4bcfe6…          ┆               ┆ dd3-f4cb50…          │
│ …          ┆ …                     ┆ …                    ┆ …             ┆ …                    │
│ 2000-01-01 ┆ ea975ea7-5bc4-4584-ad ┆ cdf36a61-82d3-4b48-b ┆ 1000.00000000 ┆ a4696e38-897d-49e8-a │
│            ┆ 79-ea24d1…            ┆ 581-6d7799…          ┆               ┆ e42-67a566…          │
│ 2000-01-01 ┆ d36a08ce-9974-4a76-a6 ┆ 3c61196e-5014-4a5d-8 ┆ 1000.00000000 ┆ 0b8eb06c-f2ba-4dd2-9 │
│            ┆ bb-7cf37f…            ┆ 7b8-9b413c…          ┆               ┆ 43f-a886fc…          │
│ 2000-01-01 ┆ ce6f327b-247e-4a50-93 ┆ 3c7f3c30-4848-48ce-b ┆ 1000.00000000 ┆ d85a1d8b-8002-4341-8 │
│            ┆ 52-66bc43…            ┆ 2a5-3fc1b9…          ┆               ┆ ed5-ec0a40…          │
│ 2000-01-01 ┆ 48164b2c-2eca-4d1e-81 ┆ b2409b2e-2e42-4c6e-8 ┆ 1000.00000000 ┆ d75e508e-5f07-40a8-9 │
│            ┆ c7-f8c811…            ┆ bc5-0b74ae…          ┆               ┆ 856-5eea87…          │
│ 2000-01-01 ┆ eec40028-ed16-4b8c-8d ┆ 29cec4b9-c146-4ff8-a ┆ 1000.00000000 ┆ 04223ee4-8499-4431-8 │
│            ┆ 96-72e70d…            ┆ 725-5cf20b…          ┆               ┆ a28-5f7ae1…          │
└────────────┴───────────────────────┴──────────────────────┴───────────────┴──────────────────────┘

In [24]:
df_market_data

shape: (120_344, 4)
┌─────────────────────────────────┬────────────┬───────────┬────────────────┐
│ instrument_id                   ┆ date       ┆ data_type ┆ value          │
│ ---                             ┆ ---        ┆ ---       ┆ ---            │
│ object                          ┆ date       ┆ str       ┆ decimal[*,10]  │
╞═════════════════════════════════╪════════════╪═══════════╪════════════════╡
│ 3c7f3c30-4848-48ce-b2a5-3fc1b9… ┆ 2025-06-30 ┆ adj_close ┆ 37.5100000000  │
│ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 2025-06-30 ┆ adj_close ┆ 88.2500000000  │
│ 491f4737-7acc-4f1a-b486-e6cc01… ┆ 2025-06-30 ┆ adj_close ┆ 110.0400000000 │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… ┆ 2025-06-30 ┆ adj_close ┆ 67.7800000000  │
│ 27fb9e0c-145d-400a-aa73-1057ff… ┆ 2025-06-30 ┆ adj_close ┆ 72.6800000000  │
│ …                               ┆ …          ┆ …         ┆ …              │
│ a421b6cb-056c-42eb-96ba-c85c8f… ┆ 2015-09-17 ┆ adj_close ┆ 44.8565564290  │
│ 727b0b7c-268d-42c4-bb48-11020f… ┆ 2015-09-17 ┆ adj_close ┆ 32.3867121235  │
│ 8cdd951a-8d3d-40bb-aa43-761fb1… ┆ 2015-09-17 ┆ adj_close ┆ 32.4630764370  │
│ 8da68d05-90e7-47c9-a779-05fce4… ┆ 2015-09-17 ┆ adj_close ┆ 6.5967287705   │
│ bc594e1a-e7b2-4b5f-bf6d-e53283… ┆ 2015-09-17 ┆ adj_close ┆ 21.3947638459  │
└─────────────────────────────────┴────────────┴───────────┴────────────────┘

In [9]:
df_investments

shape: (50, 5)
┌────────────┬───────────────────────┬──────────────────────┬───────────────┬──────────────────────┐
│ date       ┆ portfolio_id          ┆ instrument_id        ┆ quantity      ┆ id                   │
│ ---        ┆ ---                   ┆ ---                  ┆ ---           ┆ ---                  │
│ date       ┆ object                ┆ object               ┆ decimal[*,8]  ┆ object               │
╞════════════╪═══════════════════════╪══════════════════════╪═══════════════╪══════════════════════╡
│ 2000-01-01 ┆ 267b92c2-aa8a-49fe-bf ┆ c6d94933-a248-4df5-a ┆ 1000.00000000 ┆ 997f3c00-b1fa-4537-b │
│            ┆ 5c-9a2d2c…            ┆ 56e-b2c0c0…          ┆               ┆ 247-e0b5b8…          │
│ 2000-01-01 ┆ 73b9f260-1100-469b-99 ┆ 56cfb131-8c13-4e90-a ┆ 1000.00000000 ┆ 656b13a9-cc85-4b75-a │
│            ┆ a2-3a5f9e…            ┆ 0e9-55f93e…          ┆               ┆ 533-c3abd9…          │
│ 2000-01-01 ┆ 4ff1baf0-73ed-4345-98 ┆ f48b1e9f-e2d6-442a-a ┆ 1000.00000000 ┆ 49d56add-5e02-46b8-a │
│            ┆ 05-eb35a9…            ┆ cf6-2ba362…          ┆               ┆ 664-183bae…          │
│ 2000-01-01 ┆ b56a59f5-0e5d-4e2c-92 ┆ 559e6146-595c-4ea6-a ┆ 1000.00000000 ┆ d4eb3878-8a20-4959-a │
│            ┆ cd-61236f…            ┆ 489-0415f4…          ┆               ┆ 220-702fb9…          │
│ 2000-01-01 ┆ 7980bbb5-f4e8-43d5-a0 ┆ 7edd1534-ecb5-4a73-a ┆ 1000.00000000 ┆ 3dca983e-6c7c-4eff-b │
│            ┆ a8-2cde41…            ┆ 3b0-4bcfe6…          ┆               ┆ dd3-f4cb50…          │
│ …          ┆ …                     ┆ …                    ┆ …             ┆ …                    │
│ 2000-01-01 ┆ ea975ea7-5bc4-4584-ad ┆ cdf36a61-82d3-4b48-b ┆ 1000.00000000 ┆ a4696e38-897d-49e8-a │
│            ┆ 79-ea24d1…            ┆ 581-6d7799…          ┆               ┆ e42-67a566…          │
│ 2000-01-01 ┆ d36a08ce-9974-4a76-a6 ┆ 3c61196e-5014-4a5d-8 ┆ 1000.00000000 ┆ 0b8eb06c-f2ba-4dd2-9 │
│            ┆ bb-7cf37f…            ┆ 7b8-9b413c…          ┆               ┆ 43f-a886fc…          │
│ 2000-01-01 ┆ ce6f327b-247e-4a50-93 ┆ 3c7f3c30-4848-48ce-b ┆ 1000.00000000 ┆ d85a1d8b-8002-4341-8 │
│            ┆ 52-66bc43…            ┆ 2a5-3fc1b9…          ┆               ┆ ed5-ec0a40…          │
│ 2000-01-01 ┆ 48164b2c-2eca-4d1e-81 ┆ b2409b2e-2e42-4c6e-8 ┆ 1000.00000000 ┆ d75e508e-5f07-40a8-9 │
│            ┆ c7-f8c811…            ┆ bc5-0b74ae…          ┆               ┆ 856-5eea87…          │
│ 2000-01-01 ┆ eec40028-ed16-4b8c-8d ┆ 29cec4b9-c146-4ff8-a ┆ 1000.00000000 ┆ 04223ee4-8499-4431-8 │
│            ┆ 96-72e70d…            ┆ 725-5cf20b…          ┆               ┆ a28-5f7ae1…          │
└────────────┴───────────────────────┴──────────────────────┴───────────────┴──────────────────────┘